#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --partition=thin_course
#SBATCH --time 1:30:00
#SBATCH --output=$HOME/exp/job_%j.out
#SBATCH --error=$HOME/exp/job_%j.err

module load 2025
module load Python/3.13.1-GCCcore-14.2.0
module load matplotlib/3.10.3-gfbf-2025a


OUTPUT_DIR = "/scratch-shared/${USER}/data"
source my_venv/bin/activate


python $HOME/exp/batch_test.py OUTPUT_DIR

scp -r OUTPUT_DIR $HOME/exp